insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('1','TG_MA','NXB_KD',N'Những ngày thứ ba với thầy Morrie','65','52000','Văn học nước ngoài')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('2','TG_JL','NXB_KD',N'Thế giới tương lai - Nuôi nhân loại','50','60200','Khoa học')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('3','TG_TH','NXB_KD',N'Dế Mèn phiêu lưu ký','125','35000','Văn học Việt Nam')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('4','TG_VTP','NXB_KD',N'Số đỏ','131','42000','Văn học Việt Nam')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('5','TG_NNA','NXB_T',N'Còn chút gì để nhớ','60','33000','Truyện dài')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('6','TG_TX','NXB_T',N'Những con đường của ánh sáng','160','80000','Khoa học')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('7','TG_NNT','NXB_T',N'Vừa nhắm mắt vừa mở cửa sổ','125','45000','Truyện dài')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('8','TG_SH','NXB_T',N'Lược sử thời gian','90','115000','Khoa học')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('9','TG_SH','NXB_T',N'Vũ trụ trong vỏ hạt dẻ','92','110000','Khoa học')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('10','TG_CG','NXB_PNVN',N'Tiếng thét dưới băng','80','32000','Văn học nước ngoài')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('11','TG_NQM','NXB_PNVN',N'Bí quyết để thành công ở trường đại học','50','50000','Kỹ năng sống')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('12','TG_TH','NXB_NN',N'Sự im lặng của bầy cừu','135','92000','Trinh thám')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('13','TG_TH','NXB_NN',N'Rồng đỏ','68','114750','Tâm lý')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('14','TG_NNA','NXB_DTB',N'Tôi thấy hoa vàng trên cỏ xanh','160','125500','Truyện thiếu nhi')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('15','TG_TH','NXB_DTB',N'Bách khoa tri thức dành cho trẻ em','75','60000','Khoa học')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('16','TG_TV','NXB_DTB',N'Gió nam thầm thì','110','86000','Truyện dài')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('17','TG_AG','NXB_VH',N'Nghìn lẻ một đêm','100','204000','Văn học nước ngoài')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('18','TG_ACD','NXB_VH',N'Những cuộc phiêu lưu của Sherlock Holmes','72','63200','Trinh thám')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('19','TG_YA','NXB_VH',N'Another','70','160000','Kinh dị')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('20','TG_VT','NXB_TH',N'Không tự khinh bỉ, không tự phí hoài','47','109000','Kỹ năng sống')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('21','TG_VT','NXB_TH',N'Bạn đắt giá bao nhiêu','64','96000','Kỹ năng sống')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('22','TG_VT','NXB_TH',N'Không sợ chậm, chỉ sợ dừng','81','94000','Kỹ năng sống')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('23','TG_VT','NXB_TH',N'Lấy tình thâm để đổi đầu bạc','98','129000','Kỹ năng sống')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('24','TG_KL','NXB_DT',N'Thiên tài tập thể','200','89600','Tâm lý')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('25','TG_LCY','NXB_TG',N'Đông Nam á - chặng đường dài phía trước','135','76000','Văn học nước ngoài')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('26','TG_LT','NXB_TG',N'To be a Woman Doctor in Vietnam','60','90000','Tâm lý')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('27','TG_KG','NXB_TG',N'Âm thanh của sự im lặng','27','98000','Kinh dị')											
insert into Sach(MaSach,MaTG,MaNXB,TenSach,SoLuongSach,Gia,TheLoai) values ('28','TG_CM','NXB_TG',N'Thiên tài bên trái, kẻ điên bên phải','46','123000','Tâm lý')											